export const CARD_TYPES = [
  "secret",
  "deduce",
  "peek",
  "swap",
  "share",
  "rotate",
  "rumor",
  "decoy",
  "observe",
  "again",
  "chaos",
  "ally",
  "footprint",
] as const;

export type CardType = (typeof CARD_TYPES)[number];
export type CharacterId = "sheep" | "hamster" | "tanuki" | "wolf" | "penguin";
export type CardCategory = "information" | "exchange" | "deduction" | "defense" | "special";

export const CARD_CATEGORY_LABELS: Record<CardCategory, string> = {
  information: "情報",
  exchange: "交換",
  deduction: "推理",
  defense: "防御",
  special: "特殊",
};

export interface CardDefinition {
  id: CardType;
  name: string;
  category: CardCategory;
  shortDescription: string;
  description: string;
  cutInText: string;
  target: "none" | "other-player" | "any-player" | "all-players";
  targetVisibility: "none" | "public" | "participants";
  character: CharacterId;
  art: string;
  accent: string;
}

export const CARD_DEFINITIONS: Record<CardType, CardDefinition> = {
  secret: {
    id: "secret",
    name: "ひみつ",
    category: "special",
    shortDescription: "みんなが探す、たった1枚のカード",
    description: "このカードの現在の持ち主が、みんなの探している『ひみつ』の持ち主です。直接は使えず、交換で人から人へ移動します。",
    cutInText: "ひみつは静かにめぐる",
    target: "none",
    targetVisibility: "none",
    character: "wolf",
    art: "/assets/characters/card-art/secret.png?v=visual3",
    accent: "#80639b",
  },
  deduce: {
    id: "deduce",
    name: "みぬく",
    category: "deduction",
    shortDescription: "ひみつの持ち主を指名する",
    description: "全員が1回行動したあと、『ひみつ』を持っていると思う人を1人指名します。正解なら即勝利。すべて外れると、その時点の持ち主が逃げ切り勝ちです。",
    cutInText: "そのひみつ、みぬいた！",
    target: "other-player",
    targetVisibility: "public",
    character: "tanuki",
    art: "/assets/characters/card-art/deduce.png?v=visual3",
    accent: "#d5675e",
  },
  peek: {
    id: "peek",
    name: "ちらり",
    category: "information",
    shortDescription: "相手のカードを1枚だけ見る",
    description: "ほかの人を1人選び、手札からランダムな1枚を自分だけ見ます。見たカードの内容と対象者はほかの人に公開されません。",
    cutInText: "ほんの少しだけ、ちらり",
    target: "other-player",
    targetVisibility: "participants",
    character: "sheep",
    art: "/assets/characters/card-art/peek.png?v=visual3",
    accent: "#4f7fa8",
  },
  swap: {
    id: "swap",
    name: "こっそり交換",
    category: "exchange",
    shortDescription: "相手とランダムに1枚交換",
    description: "選んだ人と、手札をランダムに1枚ずつ交換します。交換したカードの内容と対象者はほかの人に公開されません。",
    cutInText: "気づかれないように、そっと",
    target: "other-player",
    targetVisibility: "participants",
    character: "tanuki",
    art: "/assets/characters/card-art/swap.png?v=visual3",
    accent: "#b37a3e",
  },
  share: {
    id: "share",
    name: "おすそわけ",
    category: "exchange",
    shortDescription: "お互いに選んだ1枚を交換",
    description: "選んだ人と、お互いに渡すカードを1枚ずつ選んで交換します。カードの内容と対象者は当事者だけの情報です。",
    cutInText: "はい、これをどうぞ",
    target: "other-player",
    targetVisibility: "participants",
    character: "hamster",
    art: "/assets/characters/card-art/share.png?v=visual3",
    accent: "#b37a3e",
  },
  rotate: {
    id: "rotate",
    name: "ぐるっと回す",
    category: "exchange",
    shortDescription: "全員の1枚を左どなりへ回す",
    description: "全員が手札から1枚を選び、そろったら席番号が次の人（左どなり）へ同時に渡します。選んだカードの内容は公開されません。",
    cutInText: "ぐるっと、ひとつ隣へ！",
    target: "all-players",
    targetVisibility: "none",
    character: "penguin",
    art: "/assets/characters/card-art/rotate.png?v=visual3",
    accent: "#b37a3e",
  },
  rumor: {
    id: "rumor",
    name: "うわさ",
    category: "information",
    shortDescription: "本当を含む候補をみんなに公開",
    description: "本当の持ち主を必ず含む候補を、3〜4人なら2人、5〜8人なら3人公開します。候補は全員が確認できます。",
    cutInText: "こんなうわさ、聞いたよ",
    target: "none",
    targetVisibility: "none",
    character: "sheep",
    art: "/assets/characters/card-art/rumor.png?v=visual3",
    accent: "#4f7fa8",
  },
  decoy: {
    id: "decoy",
    name: "おとり",
    category: "defense",
    shortDescription: "持っているだけで、みぬくを1回防ぐ",
    description: "手札にある間は常に有効です。『みぬく』の対象になったとき自動で公開して捨て、判定を1回取り消します。自分の番に使う場合は効果なしで捨てます。",
    cutInText: "その推理、こっちへどうぞ！",
    target: "none",
    targetVisibility: "public",
    character: "tanuki",
    art: "/assets/characters/card-art/decoy.png?v=visual3",
    accent: "#5e8d68",
  },
  observe: {
    id: "observe",
    name: "じっくり観察",
    category: "information",
    shortDescription: "相手の全手札を見る代わりに1枚見せる",
    description: "相手の手札を全部見る代わりに、自分の手札からランダムな1枚を相手に見られます。見た内容と対象者は当事者だけの情報です。",
    cutInText: "じっくり見れば、わかるはず",
    target: "other-player",
    targetVisibility: "participants",
    character: "wolf",
    art: "/assets/characters/card-art/observe.png?v=visual3",
    accent: "#4f7fa8",
  },
  again: {
    id: "again",
    name: "手もどし",
    category: "special",
    shortDescription: "自分が使った通常カードを1枚回収",
    description: "自分が以前に使った『ちらり・こっそり交換・おすそわけ・うわさ』から1枚を選び、手札へ戻します。回収後はターン終了です。候補がなければ効果なしで捨てられます。",
    cutInText: "あの手を、もう一度だけ",
    target: "none",
    targetVisibility: "none",
    character: "penguin",
    art: "/assets/characters/card-art/again.png?v=visual3",
    accent: "#80639b",
  },
  chaos: {
    id: "chaos",
    name: "大混乱",
    category: "special",
    shortDescription: "全員の手札をランダムに配り直す",
    description: "全員の手札を集め、各自の枚数を保ったままランダムに配り直します。その後、本当の持ち主を含む2〜3人の候補を全員に公開します。",
    cutInText: "どこに行くかは、だれにもわからない！",
    target: "none",
    targetVisibility: "none",
    character: "hamster",
    art: "/assets/characters/card-art/chaos.png?v=visual3",
    accent: "#80639b",
  },
  ally: {
    id: "ally",
    name: "なかま",
    category: "special",
    shortDescription: "ひみつ側のなかまになる",
    description: "使うと全員に公開され、このゲーム中ずっと『ひみつ側』になります。ひみつ側が逃げ切れば共同勝利です。『みぬく』は勝敗を決めず、自分だけが結果を確認する偵察になります。",
    cutInText: "ここからは、ひみつのなかま",
    target: "none",
    targetVisibility: "none",
    character: "wolf",
    art: "/assets/characters/card-art/ally.png?v=rules4",
    accent: "#75508f",
  },
  footprint: {
    id: "footprint",
    name: "あしあと",
    category: "information",
    shortDescription: "選んだ人と両どなりを調べる",
    description: "1人を選び、その人と左右どなりの合計3人の中に、現在の『ひみつ』の持ち主がいるかを全員に公開します。7人以上のゲームで登場します。",
    cutInText: "このあたりに、あしあとがあるよ",
    target: "any-player",
    targetVisibility: "public",
    character: "sheep",
    art: "/assets/characters/card-art/footprint.png?v=rules4",
    accent: "#4f7fa8",
  },
};

export const DECK_COUNTS: Record<number, Partial<Record<CardType, number>>> = {
  3: { secret: 1, deduce: 2, peek: 2, swap: 1, share: 2, rotate: 1, rumor: 1, decoy: 1, again: 1 },
  4: { secret: 1, deduce: 2, peek: 3, swap: 2, share: 3, rotate: 2, rumor: 1, decoy: 1, again: 1 },
  5: { secret: 1, deduce: 3, peek: 3, swap: 2, share: 3, rotate: 2, rumor: 2, decoy: 1, observe: 1, again: 1, ally: 1 },
  6: { secret: 1, deduce: 4, peek: 3, swap: 3, share: 3, rotate: 3, rumor: 2, decoy: 1, observe: 1, again: 1, chaos: 1, ally: 1 },
  7: { secret: 1, deduce: 4, peek: 4, swap: 4, share: 3, rotate: 4, rumor: 2, decoy: 1, observe: 1, again: 1, chaos: 1, ally: 1, footprint: 1 },
  8: { secret: 1, deduce: 5, peek: 5, swap: 4, share: 4, rotate: 4, rumor: 3, decoy: 1, observe: 1, again: 1, chaos: 1, ally: 1, footprint: 1 },
};

export const START_CARD_DEFINITION = {
  name: "みつけた！",
  shortDescription: "このカードを受け取った人が最初の発見者",
  description: "ゲーム開始前に1人へ渡される特別なスタートカードです。受け取った人が事件を発表し、最初のターンを担当します。通常の手札には入りません。",
  art: "/assets/characters/card-art/start.png?v=rules4",
  accent: "#d08a3f",
} as const;
